theme: minima
title: Abound Companies Software Development Blog
author: Frenel Titular
email: frenel@aboundhub.com
description: > # this means to ignore newlines until "baseurl:"
  Abound Companies is an all-in-one company for Real Estate solutions and our mission is to help our clients to get the best services for their mortgage and real estate needs.
# social links
twitter_username: @freneltitular
github_username:  @tfrenel45
show_excerpts: true # set to false to remove excerpts on the homepage
